/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2017-11-18 19:01:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class form_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/tags/campoData.tag", Long.valueOf(1511031562000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<title>Horizontal Nav & Subnav for Bootstrap</title>\n");
      out.write("\t<script\n");
      out.write("\t\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js\"></script>\n");
      out.write("\t<script src=\"http://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.min.js\" type=\"text/javascript\"></script>\n");
      out.write("    <script src=\"http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js\" type=\"text/javascript\"></script>\n");
      out.write("    <script src=\"http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.5.1/moment.min.js\" type=\"text/javascript\"></script>\n");
      out.write("    <script src=\"http://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/3.0.0/js/bootstrap-datetimepicker.min.js\" type=\"text/javascript\"></script>  \n");
      out.write("    <script src=\"http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.4.0/lang/en-gb.js\" type=\"text/javascript\"></script>\n");
      out.write("\n");
      out.write("<link\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("<link\n");
      out.write("\thref=\"https://getbootstrap.com/assets/css/ie10-viewport-bug-workaround.css\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\n");
      out.write("<!--[if lt IE 9]>\n");
      out.write("      <script src=\"https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js\"></script>\n");
      out.write("      <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\n");
      out.write("    <![endif]-->\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<nav class=\"navbar navbar-inverse navbar-fixed-top\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"navbar-header\">\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\"\n");
      out.write("\t\t\t\t\tdata-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\"\n");
      out.write("\t\t\t\t\taria-controls=\"navbar\">\n");
      out.write("\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\n");
      out.write("\t\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\n");
      out.write("\t\t\t\t\t\tclass=\"icon-bar\"></span>\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"#\">BRAND X</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"navbar-collapse collapse navbar-right main-nav\"\n");
      out.write("\t\t\t\tid=\"navbar\">\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav \">\n");
      out.write("\t\t\t\t\t<li id=\"sub-1\"><a href=\"#products\">Products &amp; Services</a></li>\n");
      out.write("\t\t\t\t\t<li id=\"sub-2\"><a href=\"#features\">Features</a></li>\n");
      out.write("\t\t\t\t\t<li id=\"sub-3\"><a href=\"#about\">About</a></li>\n");
      out.write("\t\t\t\t\t<li id=\"sub-4\"><a href=\"#faqs\">FAQS</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<form class=\"navbar-form navbar-right\">\n");
      out.write("\t\t\t\t\t<button type=\"submit\" class=\"btn btn-warning\">CALL 2\n");
      out.write("\t\t\t\t\t\tACTION</button>\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t\t<div class=\"bottom-arrow\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!--/.navbar-collapse -->\n");
      out.write("\t\t</div>\n");
      out.write("\t</nav>\n");
      out.write("\n");
      out.write("\t<!-- Sub navbar -->\n");
      out.write("\t<nav class=\"subnavbar navbar navbar-fixed-top\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"navbar-collapse collapse navbar-right\" id=\"subnavbar\">\n");
      out.write("\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav sub-1\" style=\"display: none;\">\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a href=\"#sprockets\">Sprockets</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#housewares\">Housewares</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#widgets\">Widgets &amp; Whatnots</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#tools\">Tools</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#utilities\">Utilities</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav sub-2\" style=\"display: none;\">http://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.min.js\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a href=\"#marketing\">Marketing</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#sales\">Sales</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#service\">Customer Service</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#security\">Security</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#legal\">Rights &amp; Privacy</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav sub-3\" style=\"display: none;\">\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a href=\"#w1\">Who</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#w2\">What</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#w3\">When</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#w4\">Where</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#w5\">Why</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav sub-4\" style=\"display: none;\">\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a href=\"#g1\">General</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#g2\">Social Networking</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#g3\">Servicing</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#g4\">Plans</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!--/.navbar-collapse -->\n");
      out.write("\t\t</div>\n");
      out.write("\t</nav>\n");
      out.write("\t<div class=\"container\" style=\"margin-top: 65px;\">\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<div class=\"col-sm-12\">\n");
      out.write("\t\t\t\t<form action=\"adicionaContato\" method=\"post\">\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label for=\"nome\">nome:</label> <input type=\"text\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control\" id=\"nome\" name=\"nome\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label for=\"email\">Email address:</label> <input type=\"email\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control\" id=\"email\" name=\"email\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label for=\"endereco\">EndereÃ§o:</label> <input type=\"text\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control\" id=\"endereco\" name=\"endereco\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label for=\"data-de-nascimento\">Data de Nascimento:</label> \n");
      out.write("\t\t\t\t\t\t<!-- input type=\"text\" class=\"form-control\" id=\"dataDeNascimento\" name=\"dataDeNascimento\"> -->\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_caelum_005fcampoData_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary\">Submit</button>\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write(" \n");
      out.write("\t<script\n");
      out.write("\t\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js\"\n");
      out.write("\t\ttype=\"text/javascript\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_caelum_005fcampoData_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  caelum:campoData
    org.apache.jsp.tag.webcampoData_tag _jspx_th_caelum_005fcampoData_005f0 = (new org.apache.jsp.tag.webcampoData_tag());
    _jsp_instancemanager.newInstance(_jspx_th_caelum_005fcampoData_005f0);
    _jspx_th_caelum_005fcampoData_005f0.setJspContext(_jspx_page_context);
    // /form.jsp(125,6) name = id type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_caelum_005fcampoData_005f0.setId("dataNascimento");
    _jspx_th_caelum_005fcampoData_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_caelum_005fcampoData_005f0);
    return false;
  }
}
